/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author anaju
 */
public class FrSignosAnaNoite extends javax.swing.JFrame {

    /**
     * Creates new form FrSignosAnaNoite
     */
    public FrSignosAnaNoite() {
        initComponents();
        lbAries.setVisible(false);
        lbTouro.setVisible(false);
        lbAquario.setVisible(false);
        lbVirgem.setVisible(false);
        lbPeixes.setVisible(false);
        lbLibra.setVisible(false);
        lbCancer.setVisible(false);
        lbGemeos.setVisible(false);
        lbSagitario.setVisible(false);
        lbEscorpiao.setVisible(false);
        lbLeao.setVisible(false);
        lbCapricornio.setVisible(false);
    }

    public int idade(int dia, int mes, int ano) {
        LocalDate agr = LocalDate.now();
        int idade;
        int diaAtual, mesAtual, anoAtual;
        diaAtual = agr.getDayOfMonth();
        mesAtual = agr.getMonthValue();
        anoAtual = agr.getYear();

        idade = ((anoAtual * 365 + mesAtual * 12 + diaAtual) - (ano * 365 + mes * 12 + dia)) / 365;
        return idade;

    }

    public String signo(int dia, int mes, int ano) {

        String signo = "";
        if (dia >= 21 && dia <= 31 && mes == 3 || dia >= 1 && dia <= 20 && mes == 4) {
            signo = "Áries";
            lbAries.setVisible(true);

        }
        if (dia >= 21 && dia <= 30 && mes == 4 || dia >= 1 && dia <= 20 && mes == 5) {

            signo = "Touro";
            lbTouro.setVisible(true);
        }
        if (dia >= 21 && dia <= 31 && mes == 5 || dia >= 1 && dia <= 20 && mes == 6) {

            signo = "Gêmeos";
            lbGemeos.setVisible(true);
        }
        if (dia >= 21 && dia <= 30 && mes == 6 || dia >= 1 && dia <= 21 && mes == 7) {

            signo = "Câncer";
            lbCancer.setVisible(true);
        }
        if (dia >= 22 && dia <= 31 && mes == 7 || dia >= 1 && dia <= 22 && mes == 8) {

            signo = "Leão";
            lbLeao.setVisible(true);
        }
        if (dia >= 23 && dia <= 30 && mes == 8 || dia >= 1 && dia <= 22 && mes == 9) {

            signo = "Virgem";
            lbVirgem.setVisible(true);
        }
        if (dia >= 23 && dia <= 31 && mes == 9 || dia >= 1 && dia <= 22 && mes == 10) {

            signo = "Libra";
            lbLibra.setVisible(true);
        }
        if (dia >= 23 && dia <= 30 && mes == 10 || dia >= 1 && dia <= 21 && mes == 11) {

            signo = "Escorpião";
            lbEscorpiao.setVisible(true);
        }
        if (dia >= 22 && dia <= 31 && mes == 11 || dia >= 1 && dia <= 21 && mes == 12) {

            signo = "Sagitário";
            lbSagitario.setVisible(true);
        }
        if (dia >= 22 && dia <= 31 && mes == 12 || dia >= 1 && dia <= 20 && mes == 1) {

            signo = "Capricórnio";
            lbCapricornio.setVisible(true);
        }
        if (dia >= 21 && dia <= 31 && mes == 1 || dia >= 1 && dia <= 19 && mes == 2) {

            signo = "Aquário";
            lbAquario.setVisible(true);
        }
        if (dia >= 20 && dia <= 30 && mes == 2 || dia >= 1 && dia <= 20 && mes == 3) {

            signo = "Peixes";
            lbPeixes.setVisible(true);
        }

        return signo;

    }

    public static int numSortiado(int numero) {
        int numSorte;
        Random sorte = new Random();
        numSorte = (int) 1 + (int) (Math.random() * 100);
        return numSorte;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btConcluir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        rbFeminino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        cbDia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbAno = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        lbResto = new javax.swing.JLabel();
        lbAries = new javax.swing.JLabel();
        lbTouro = new javax.swing.JLabel();
        lbGemeos = new javax.swing.JLabel();
        lbVirgem = new javax.swing.JLabel();
        lbLibra = new javax.swing.JLabel();
        lbSagitario = new javax.swing.JLabel();
        lbCancer = new javax.swing.JLabel();
        lbPeixes = new javax.swing.JLabel();
        lbAquario = new javax.swing.JLabel();
        lbLeao = new javax.swing.JLabel();
        lbEscorpiao = new javax.swing.JLabel();
        lbCapricornio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 255));
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 98, -1, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setText("Sexo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 199, -1, -1));

        jLabel3.setBackground(new java.awt.Color(153, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 51, 255));
        jLabel3.setText("Data de Nascimento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 320, -1, -1));

        btLimpar.setBackground(new java.awt.Color(255, 204, 255));
        btLimpar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(102, 0, 204));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 421, -1, -1));

        btConcluir.setBackground(new java.awt.Color(255, 204, 255));
        btConcluir.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        btConcluir.setForeground(new java.awt.Color(102, 0, 204));
        btConcluir.setText("Concluir");
        btConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btConcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 421, -1, -1));

        jLabel5.setBackground(new java.awt.Color(153, 102, 255));
        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 204));
        jLabel5.setText("Guru On-Line");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(102, 0, 204));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 144, 340, -1));

        rbFeminino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbFeminino);
        rbFeminino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbFeminino.setForeground(new java.awt.Color(102, 0, 204));
        rbFeminino.setSelected(true);
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });
        jPanel1.add(rbFeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 232, -1, -1));

        rbMasculino.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMasculino);
        rbMasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbMasculino.setForeground(new java.awt.Color(102, 0, 204));
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rbMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 264, -1, -1));

        cbDia.setBackground(new java.awt.Color(153, 102, 255));
        cbDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDia.setForeground(new java.awt.Color(102, 0, 153));
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiaActionPerformed(evt);
            }
        });
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 351, -1, -1));

        cbMes.setBackground(new java.awt.Color(153, 102, 255));
        cbMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMes.setForeground(new java.awt.Color(102, 0, 153));
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mês", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });
        jPanel1.add(cbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 351, -1, -1));

        cbAno.setBackground(new java.awt.Color(153, 102, 255));
        cbAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbAno.setForeground(new java.awt.Color(102, 0, 153));
        cbAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ano", "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        jPanel1.add(cbAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 351, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/astroconselho.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 300, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 34, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 311, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/Guru.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        lbResultado.setBackground(new java.awt.Color(255, 255, 255));
        lbResultado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbResultado.setForeground(new java.awt.Color(255, 255, 255));
        lbResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 580, 30));

        lbResto.setBackground(new java.awt.Color(255, 255, 255));
        lbResto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbResto.setForeground(new java.awt.Color(255, 255, 255));
        lbResto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lbResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 580, 25));

        lbAries.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        lbAries.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/aries.png"))); // NOI18N
        jPanel1.add(lbAries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 770, 90));

        lbTouro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/touro.png"))); // NOI18N
        jPanel1.add(lbTouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbGemeos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/gemeos.png"))); // NOI18N
        jPanel1.add(lbGemeos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbVirgem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/virgem.png"))); // NOI18N
        jPanel1.add(lbVirgem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbLibra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/libra.png"))); // NOI18N
        jPanel1.add(lbLibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbSagitario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/sagitario.png"))); // NOI18N
        jPanel1.add(lbSagitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbCancer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/cancer.png"))); // NOI18N
        jPanel1.add(lbCancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbPeixes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/peixes.png"))); // NOI18N
        jPanel1.add(lbPeixes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbAquario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/aquario.png"))); // NOI18N
        jPanel1.add(lbAquario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbLeao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/leao.png"))); // NOI18N
        jPanel1.add(lbLeao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 750, 100));

        lbEscorpiao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/escorpiao.png"))); // NOI18N
        jPanel1.add(lbEscorpiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 680, 100));

        lbCapricornio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ulbra/view/imagens/capricornio.png"))); // NOI18N
        jPanel1.add(lbCapricornio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 484, 680, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void btConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConcluirActionPerformed
        DecimalFormat f = new DecimalFormat("0");
        String nome, signoCalculado;
        int mes, ano, dia;
        
         LocalDate agr = LocalDate.now();
        int diaAtual = agr.getDayOfMonth();
        int mesAtual = agr.getMonthValue();
        int anoAtual = agr.getYear();


        dia = cbDia.getSelectedIndex();
        mes = cbMes.getSelectedIndex();
        ano = Integer.parseInt(cbAno.getSelectedItem().toString());
        //JOptionPane.showMessageDialog(null, ano);

        nome = txtNome.getText();
        signoCalculado = signo(dia, mes, ano);
        int i = idade(dia, mes, ano);

        //randomizando a cor
        String cores[] = {"Azul", "Amarelo", "Verde", "Roxo", "Laranja", "Rosa", "Ciano", "Preto", "Branco", "Marrom", "Bege", "Cinza"};
        Random random = new Random();
        int numCor = random.nextInt(cores.length);
        String corRandom = cores[numCor];
        //randomizado

        if (txtNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Insira seu nome, por favor.");
        } else if (cbDia.getSelectedIndex() == 0 || cbMes.getSelectedIndex() == 0 || cbAno.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Insira sua data de aniversário, por favor.");
        } else if (dia>diaAtual && mes>=mesAtual && ano>=anoAtual) {
             JOptionPane.showMessageDialog(null, "Insira sua data de aniversário, por favor.");
        } else if ((ano % 100 != 0 && ano % 4 == 0 || ano % 400 == 0) && mes==2 && dia>29){
             JOptionPane.showMessageDialog(null, "Insira sua data de aniversário, por favor.");
        } else if (txtNome.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Insira seu nome completo, por favor.");
        } else if ((mes == 4 || mes == 6 || mes == 9 || mes == 11) && dia > 30) {
            JOptionPane.showMessageDialog(null, "Insira a data correta, por favor.");
        } else if (mes == 2 && dia > 28) {
            JOptionPane.showMessageDialog(null, "Insira a data correta, por favor.");
        } else {
            if (rbMasculino.isSelected()) {
                lbResultado.setText("Sr. " + nome + " nascido no dia " + dia + "/" + mes + "/" + ano + ", você é do signo de " + signoCalculado + " e tem " + i + " anos.");
                lbResto.setText("Seu número da sorte é: " + numSortiado(100) + " e sua cor da sorte é: " + corRandom);
            } else if (rbFeminino.isSelected()) {
                lbResultado.setText("Sra. " + nome + " nascida no dia " + dia + "/" + mes + "/" + ano + ", você é do signo de " + signoCalculado + " e tem " + i + " anos.");
                lbResto.setText("Seu número da sorte é: " + numSortiado(100) + " e sua cor da sorte é: " + corRandom);
            }

        }
    }//GEN-LAST:event_btConcluirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        txtNome.setText(null);
        cbDia.setSelectedIndex(0);
        cbMes.setSelectedIndex(0);
        cbAno.setSelectedIndex(0);
        rbMasculino.setSelected(false);
        rbFeminino.setSelected(false);
        lbResultado.setText(null);
        lbResto.setText(null);
        lbAries.setVisible(false);
        lbTouro.setVisible(false);
        lbAquario.setVisible(false);
        lbVirgem.setVisible(false);
        lbPeixes.setVisible(false);
        lbLibra.setVisible(false);
        lbCancer.setVisible(false);
        lbGemeos.setVisible(false);
        lbSagitario.setVisible(false);
        lbEscorpiao.setVisible(false);
        lbLeao.setVisible(false);
        lbCapricornio.setVisible(false);

    }//GEN-LAST:event_btLimparActionPerformed

    private void cbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDiaActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrSignosAnaNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrSignosAnaNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrSignosAnaNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrSignosAnaNoite.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrSignosAnaNoite().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAquario;
    private javax.swing.JLabel lbAries;
    private javax.swing.JLabel lbCancer;
    private javax.swing.JLabel lbCapricornio;
    private javax.swing.JLabel lbEscorpiao;
    private javax.swing.JLabel lbGemeos;
    private javax.swing.JLabel lbLeao;
    private javax.swing.JLabel lbLibra;
    private javax.swing.JLabel lbPeixes;
    private javax.swing.JLabel lbResto;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbSagitario;
    private javax.swing.JLabel lbTouro;
    private javax.swing.JLabel lbVirgem;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
